[package]
name = "workflowstatus"
version = "0.1.0"
authors = ["Alexander Worton <alexander@ajsworton.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }